C++ deplex library
achains/fast-CAPE pull request #6
Opened 2022-11-14 21:43 UTC by achains

2022-11-17 13:34 UTC, anastasiia-kornilova requested changes

2022-11-17 13:34 UTC, anastasiia-kornilova commented on CMakeLists.txt
> +option(BUILD_EXAMPLES "Build C++ examples of CAPE usage" ON)
of deplex?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/CMakeLists.txt
> +find_package(OpenCV REQUIRED)
Nothing is said that opencv and eigen should be preinstalled, at least in readme

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/CMakeLists.txt
> +find_package(OpenCV REQUIRED)
Btw, how to build for different platforms if you use pre installed packages?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/CMakeLists.txt
> +target_link_libraries(${TARGET_NAME} PUBLIC ${OpenCV_LIBS})
Looks like we don't need all opencv libs, let's specify which one exactly are required

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/CMakeLists.txt
> +target_link_libraries(${TARGET_NAME} PUBLIC ${OpenCV_LIBS})
Why do we need to link them public?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/CMakeLists.txt
> +set(TARGET_INCLUDE_FOLDER ${CMAKE_CURRENT_SOURCE_DIR}/include)
Don't think that all headers should be in lib interface

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/config.hpp
> +std::map<std::string, std::string> iniLoad(std::string iniFileName) {
Why parameter not a const reference?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/config.hpp
> +namespace ini_read {
Are there any libraries to parse ini-files? Rather than writing your own?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/config.hpp
> +std::map<std::string, std::string> iniLoad(std::string iniFileName) {
Let's not mix camelCase, let's better use google c++ styleguide with underscores

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/config.hpp
> +    size_t eqPos = line.find_first_of("=");
One more combination of styleguide

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/config.hpp
> +Config::Config(std::map<std::string, std::string> const& param_map)
No, it is not good practice to combine implementation with interface, separate please

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/config.hpp
> +    : _param_map(ini_read::iniLoad(config_path)) {}
Why this method is not private function of Config class?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/config.hpp
> +    std::cerr << "Error! Couldn't open ini file: " << iniFileName << '\n';
Why not an exception here? Let's choose common strategy for using either stderr either exception

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/config.hpp
> +      "Invalid value for parameter 'doRefinement'. Allowed values: "
Wtf, what if there are other parameters except doRefinement that has also boolean type?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/histogram.hpp
> +      _nr_bins(nr_bins_per_coord * nr_bins_per_coord),
No implementation in header file

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/histogram.hpp
> +  std::vector<int32_t> _bins;
Google style guide expects underscore in the end of variable

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/histogram.hpp
> +#ifndef BITSET_SIZE
Why do we need this?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/config.hpp
> +    return {};
std optional is better for such cases

2022-11-17 13:34 UTC, anastasiia-kornilova commented on .clang-format
> +BasedOnStyle: google
Why not cpplint that is more targeted to C++ code style?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/histogram.hpp
> +      _nr_points(static_cast<int32_t>(P.rows())),
Let's move int_32 to internal type, it is copied everywhere, what if it will be changed?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/histogram.hpp
> +  Histogram(int32_t nr_bins_per_coord, Eigen::MatrixXd const& P,
nr is not so readable and commonly used as cnt, let's change

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/histogram.hpp
> +       i = mask._Find_next(i)) {
Why do you need new line here? You are out of 120 standard symbols? Difficult to read

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/histogram.hpp
> +Histogram::Histogram(int32_t nr_bins_per_coord, Eigen::MatrixXd const& P,
What is matrix P for? Please, specify in more proper naming

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/planeseg.hpp
> +#pragma once
plane_seg? What is the difference with plane extraction? Not clear at all

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/histogram.hpp
> +class Histogram {
Add comment on what data this histogram operates -- points/normals/etc

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/plane_extraction.h
> +class CAPE {
Wtf, algo and file have different names

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/plane_extraction.h
> +  cv::Mat process(Eigen::MatrixXf const& pcd_array);
Maybe interface should not depend on opencv? Let's operate with raw Eigen data and then do conversions

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/plane_extraction.h
> +  void organizeByCell(Eigen::MatrixXf const& pcd_array, Eigen::MatrixXf* out);
Separate with empty lines all function declarations, difficult to red

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/include/deplex/planeseg.hpp
> +  struct Stats {
Move to separate file

2022-11-17 13:34 UTC, anastasiia-kornilova commented on scripts/readers/tum_reader.py
> +    points = np.zeros((camera_intrinsics.width * camera_intrinsics.height, 3))
It could be easily converted using open3d read_depth_image, strange things below are not required

2022-11-17 13:34 UTC, anastasiia-kornilova commented on scripts/readers/tum_reader.py
> +    image = cv2.imread(depth_path, cv2.IMREAD_ANYDEPTH)
Also, simply could be done by open3d, since you already use it here

2022-11-17 13:34 UTC, anastasiia-kornilova commented on data/configs/ICL_living_room.ini
> +[Parameters]
Let's move configs to algorithm folder, they should be distributed with algo

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/src/plane_extraction.cpp
> +const config::Config CAPE::__default_config{
Why not to read it from file? If you have file configs for others, let's have also file for default

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/src/plane_extraction.cpp
> +      _nr_horizontal_cells(image_width / config.getInt("patchSize")),
What will happen if image_width is not multiple of patchsize?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/src/plane_extraction.cpp
> +      _nr_horizontal_cells(image_width / config.getInt("patchSize")),
Also, there is implicit conversion from float to int, not good.

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/src/plane_extraction.cpp
> +  Eigen::MatrixXf organized_array(pcd_array.rows(), pcd_array.cols());
Let's name it cell_array and then splitIntoCells

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/src/plane_extraction.cpp
> +  // 3. Compute cell dist tols
What is tols? Let's rename to tolerance if that is it

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/src/plane_extraction.cpp
> +      _nr_horizontal_cells(image_width / config.getInt("patchSize")),
Maybe better to keep patch_size as class variable? not to access it from config everytime, it is oftenly used

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/src/plane_extraction.cpp
> +void CAPE::organizeByCell(Eigen::MatrixXf const& pcd_array,
Please, specify in comment what form this array will have, I mean how data inside is organized

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/src/plane_extraction.cpp
> +  vectorToCSV(labels, save_path);
If this is for debug why it is not under the flag?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/src/plane_extraction.cpp
> +          stacked_cell_id, cell_width, cell_height, pcd_array, _config);
Why PlaneSeg should know about whole config?

2022-11-17 13:34 UTC, anastasiia-kornilova commented on cpp/src/plane_extraction.cpp
> +  cleanArtifacts();
Why do we need to keep so many things as class variables, not having them simply as arguments?

2022-11-22 19:16 UTC, achains commented on CMakeLists.txt
> +option(BUILD_EXAMPLES "Build C++ examples of CAPE usage" ON)
fixed

2022-11-22 19:21 UTC, achains commented on cpp/CMakeLists.txt
> +find_package(OpenCV REQUIRED)
It is temporary on current stage. I will ensure later that both OpenCV and Eigen are fetched by CMake on Python package deployment step.

2022-11-22 19:33 UTC, achains commented on cpp/include/deplex/config.hpp
> +namespace ini_read {
Why should we increase build time with downloading another 3rd-party library just for one small func? We don't need that much functionality to work with single .ini of ~15 lines

2022-11-22 19:50 UTC, achains commented on cpp/include/deplex/config.hpp
> +    : _param_map(ini_read::iniLoad(config_path)) {}
Reasonable

2022-11-22 19:50 UTC, achains commented on cpp/include/deplex/config.hpp
> +    std::cerr << "Error! Couldn't open ini file: " << iniFileName << '\n';
fixed

2022-11-22 19:52 UTC, achains commented on cpp/include/deplex/config.hpp
> +      "Invalid value for parameter 'doRefinement'. Allowed values: "
brain lag, fixed

2022-11-22 19:56 UTC, achains commented on cpp/include/deplex/histogram.hpp
> +#ifndef BITSET_SIZE
Bitset size has to be defined at compile time. As alternatives we have boost::dynamic_bitset or std::vector\<bool\>, but they both are noticeably slower. Proper tests should be held later at performance-tune stage

2022-11-22 20:00 UTC, achains commented on cpp/include/deplex/config.hpp
> +    return {};
std::optional leads to limitation of minimum compiler version on macos. Anyway we don't need it here anymore.

2022-11-22 20:17 UTC, achains commented on cpp/include/deplex/plane_extraction.h
> +class CAPE {
fixed

2022-11-22 20:19 UTC, achains commented on cpp/include/deplex/plane_extraction.h
> +  cv::Mat process(Eigen::MatrixXf const& pcd_array);
That's right, it shouldn't. Labels are now returned as Eigen integer Vector1D.

2022-11-22 20:32 UTC, achains commented on scripts/readers/tum_reader.py
> +    points = np.zeros((camera_intrinsics.width * camera_intrinsics.height, 3))
1. Took code from one of DmiitriyJarosh projects with readers
2. These readers is needed only for my local debug and should be later excluded from project

2022-11-22 20:32 UTC, achains commented on scripts/readers/tum_reader.py
> +    image = cv2.imread(depth_path, cv2.IMREAD_ANYDEPTH)
1. Took code from one of DmiitriyJarosh projects with readers
2. These readers is needed only for my local debug and should be later excluded from project

2022-11-25 11:47 UTC, achains commented on cpp/CMakeLists.txt
> +set(TARGET_INCLUDE_FOLDER ${CMAKE_CURRENT_SOURCE_DIR}/include)
All headers we now have are public and they have to be public. Private headers might be added later.

2022-11-25 11:47 UTC, achains commented on cpp/include/deplex/config.hpp
> +std::map<std::string, std::string> iniLoad(std::string iniFileName) {
done

2022-11-25 11:49 UTC, achains commented on cpp/include/deplex/config.hpp
> +Config::Config(std::map<std::string, std::string> const& param_map)
done

2022-11-25 11:49 UTC, achains commented on cpp/include/deplex/histogram.hpp
> +      _nr_bins(nr_bins_per_coord * nr_bins_per_coord),
done

2022-11-25 12:18 UTC, achains commented on cpp/include/deplex/histogram.hpp
> +  std::vector<int32_t> _bins;
fixed

2022-11-25 12:23 UTC, achains commented on cpp/include/deplex/histogram.hpp
> +  Histogram(int32_t nr_bins_per_coord, Eigen::MatrixXd const& P,
Hard to agree. For me cnt is more about _counting_ smth, but in this case we have just a precalculated number of things

2022-11-25 12:25 UTC, achains commented on cpp/include/deplex/histogram.hpp
> +Histogram::Histogram(int32_t nr_bins_per_coord, Eigen::MatrixXd const& P,
Agree, renamed to 'points'

2022-11-25 12:26 UTC, achains commented on cpp/include/deplex/planeseg.hpp
> +#pragma once
Renamed to cell_segment

2022-11-25 12:32 UTC, achains commented on cpp/include/deplex/histogram.hpp
> +class Histogram {
Renamed one of parameters to 'normals', guess now it is better for understanding. I will add thorough comments later

2022-11-25 13:10 UTC, achains commented on cpp/include/deplex/plane_extraction.h
> +  void organizeByCell(Eigen::MatrixXf const& pcd_array, Eigen::MatrixXf* out);
done

2022-11-25 13:13 UTC, achains commented on cpp/src/plane_extraction.cpp
> +  vectorToCSV(labels, save_path);
fixed

2022-11-25 13:41 UTC, achains commented on cpp/include/deplex/config.hpp
> +    size_t eqPos = line.find_first_of("=");
done

2022-11-28 14:25 UTC, anastasiia-kornilova commented on cpp/CMakeLists.txt
> +find_package(OpenCV REQUIRED)
Don't see in issues

2022-11-28 14:26 UTC, anastasiia-kornilova commented on 3rd_party/CMakeLists.txt
> +if (${BUILD_PYTHON})
Let's rename for `externals`, that is more common name

2022-11-28 14:27 UTC, anastasiia-kornilova commented on CMakeLists.txt
> +add_subdirectory(cpp)
It is usually named `src`

2022-11-28 14:27 UTC, anastasiia-kornilova commented on CMakeLists.txt
> +add_subdirectory(cpp)
https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs

2022-11-28 14:27 UTC, anastasiia-kornilova commented on 3rd_party/CMakeLists.txt
> +if (${BUILD_PYTHON})
https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/pitchfork/develop/data/spec.bs

2022-11-28 14:35 UTC, anastasiia-kornilova commented on cpp/deplex/include/deplex/algorithm/cell_segment.h
> +  struct Stats {
Move to separate file, please, not to overload current one

2022-11-29 14:07 UTC, anastasiia-kornilova commented on cpp/deplex/include/deplex/algorithm/cell_segment.h
> +  bool _isHorizontalContinuous(Eigen::MatrixXf const& cell_z) const;
Fix please

2022-12-01 18:16 UTC, anastasiia-kornilova commented on cpp/deplex/src/deplex/histogram.cpp
> +Histogram::Histogram(int32_t nr_bins_per_coord, Eigen::MatrixXd const& normals, std::bitset<BITSET_SIZE> const& mask)
Why do you call it normal if actually that is spherical coordinates passing here?
Also, let's move calculation of spherical coordinates here, passing normals as argument

2023-03-21 17:25 UTC, anastasiia-kornilova requested changes

2023-03-21 17:25 UTC, anastasiia-kornilova commented on cpp/deplex/include/deplex/utils/image.h
> +class Image {
I would name it depth image

2023-03-21 17:25 UTC, anastasiia-kornilova commented on cpp/deplex/include/deplex/plane_extractor.h
> +   * @returns 1D Array, where i-th value is plane number to which refers i-th point of point cloud.
We need to say how not planar points are labelled

2023-03-21 17:25 UTC, anastasiia-kornilova commented on cpp/deplex/include/deplex/plane_extractor.h
> +  Eigen::VectorXi process(Eigen::MatrixXf const& pcd_array);
Add option to process depth image (move to issues now)

2023-03-21 17:25 UTC, anastasiia-kornilova commented on cpp/benchmark/benchmark_extractor.cpp
> + * Copyright 2022 prime-slam
License with our names (to issues)

2023-03-21 17:25 UTC, anastasiia-kornilova commented on cpp/deplex/src/deplex/plane_extractor.cpp
> +#include <queue>
Should it be upper with other imports?

2023-03-21 17:25 UTC, anastasiia-kornilova commented on cpp/deplex/src/deplex/plane_extractor.cpp
> +const config::Config PlaneExtractor::kDefaultConfig{{{"patchSize", "12"},
Why it is not moved to default constructor of Config?

2023-03-21 17:25 UTC, anastasiia-kornilova commented on cpp/deplex/src/deplex/cell_segment.cpp
> +  return disc_count < max_number_depth_disc;
We use count, or number, or cnt, or what?

2023-03-21 17:25 UTC, anastasiia-kornilova commented on cpp/deplex/src/deplex/plane_extractor.cpp
> +  Eigen::MatrixXf normals = Eigen::MatrixXf::Zero(cell_grid.size(), 3);
Why it is not in normals histogram constructor?

2023-03-21 17:25 UTC, anastasiia-kornilova commented on cpp/deplex/src/deplex/plane_extractor.cpp
> +  Eigen::MatrixXf normals = Eigen::MatrixXf::Zero(cell_grid.size(), 3);
Because of this you do double check on is it planar or not

2023-03-21 17:25 UTC, anastasiia-kornilova commented on cpp/deplex/src/deplex/plane_extractor.cpp
> +  organizeByCell(pcd_array, &organized_array);
Could it be inside CellGrid construction? I don't see other usages

2023-03-21 17:25 UTC, anastasiia-kornilova commented on cpp/deplex/src/deplex/plane_extractor.cpp
> +    std::vector<bool> activation_map(unassigned_mask.size());
Why not to return it from the `growSeed` function?

2023-05-12 06:08 UTC, achains commented on cpp/deplex/include/deplex/plane_extractor.h
> +  Eigen::VectorXi process(Eigen::MatrixXf const& pcd_array);
I believe we shouldn't do this. For this purpose we have DepthImage class that provide method to convert image and then pass points to algorithm's input.

2023-05-12 06:10 UTC, achains commented on cpp/deplex/src/deplex/cell_segment.cpp
> +  return disc_count < max_number_depth_disc;
For me count is when we incrementing variable (i.g. in a loop) and number is something constant. We can discuss it

2023-05-12 06:19 UTC, achains commented on cpp/deplex/src/deplex/plane_extractor.cpp
> +  Eigen::MatrixXf normals = Eigen::MatrixXf::Zero(cell_grid.size(), 3);
Otherwise NormalsHistogram will have a dependency on CellGrid. 
These loop passes don't add any complexity.

2023-05-13 14:50 UTC, anastasiia-kornilova approved these changes

2023-05-13 14:50 UTC, merged